from __future__ import annotations

CITY_CATALOG = {
    "San José": {
        "city_name": "San José",
        "country_code": "CR",
        "region_name": "San José",
        "latitude": 9.9281,
        "longitude": -84.0907,
        "timezone_name": "America/Costa_Rica",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Lima": {
        "city_name": "Lima",
        "country_code": "PE",
        "region_name": "Lima",
        "latitude": -12.0464,
        "longitude": -77.0428,
        "timezone_name": "America/Lima",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Santiago": {
        "city_name": "Santiago",
        "country_code": "CL",
        "region_name": "Región Metropolitana",
        "latitude": -33.4489,
        "longitude": -70.6693,
        "timezone_name": "America/Santiago",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Ciudad de México": {
        "city_name": "Ciudad de México",
        "country_code": "MX",
        "region_name": "Ciudad de México",
        "latitude": 19.4326,
        "longitude": -99.1332,
        "timezone_name": "America/Mexico_City",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Buenos Aires": {
        "city_name": "Buenos Aires",
        "country_code": "AR",
        "region_name": "Buenos Aires",
        "latitude": -34.6037,
        "longitude": -58.3816,
        "timezone_name": "America/Argentina/Buenos_Aires",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Bogotá": {
        "city_name": "Bogotá",
        "country_code": "CO",
        "region_name": "Bogotá",
        "latitude": 4.7110,
        "longitude": -74.0721,
        "timezone_name": "America/Bogota",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Quito": {
        "city_name": "Quito",
        "country_code": "EC",
        "region_name": "Pichincha",
        "latitude": -0.1807,
        "longitude": -78.4678,
        "timezone_name": "America/Guayaquil",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Montevideo": {
        "city_name": "Montevideo",
        "country_code": "UY",
        "region_name": "Montevideo",
        "latitude": -34.9011,
        "longitude": -56.1645,
        "timezone_name": "America/Montevideo",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
    "Asunción": {
        "city_name": "Asunción",
        "country_code": "PY",
        "region_name": "Asunción",
        "latitude": -25.2637,
        "longitude": -57.5759,
        "timezone_name": "America/Asuncion",
        "location_scope": "city",
        "source_system": "open_meteo",
    },
}


def get_city_location(city_key: str) -> dict:
    return CITY_CATALOG.get(city_key, CITY_CATALOG["San José"])
